#!/usr/bin/env bash

set -euo pipefail

readonly APP_ID="com.rusttavern.client"
readonly IDENTITY_FILE="packaging/flatpak/build-identity.env"
readonly PNPM_CLI="flatpak-pnpm/bin/pnpm.cjs"

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

[[ -r "$IDENTITY_FILE" ]] ||
    die "missing build identity; invoke packaging/flatpak/build.sh"

# The file is generated by packaging/flatpak/build.sh after validating both values.
# shellcheck disable=SC1090
source "$IDENTITY_FILE"

[[ "${RUSTTAVERN_BUILD_BRANCH:-}" =~ ^[A-Za-z0-9._/-]+$ ]] ||
    die "invalid RUSTTAVERN_BUILD_BRANCH"
[[ "${RUSTTAVERN_BUILD_REVISION:-}" =~ ^[0-9A-Fa-f]{7,64}$ ]] ||
    die "invalid RUSTTAVERN_BUILD_REVISION"
[[ -r "$PNPM_CLI" ]] ||
    die "missing pinned pnpm CLI"

export RUSTTAVERN_BUILD_BRANCH
export RUSTTAVERN_BUILD_REVISION

mkdir -p .flatpak-bin
ln -s "../$PNPM_CLI" .flatpak-bin/pnpm
export PATH="$PWD/.flatpak-bin:$PATH"

pnpm install --offline --frozen-lockfile
cargo fetch --offline --locked --manifest-path Cargo.toml

node scripts/build-server.mjs --skip-web-build --out-dir "$PWD/.flatpak-release"

# The server release layout is a flat directory: binary + src/ + default/.
# Install it into the Flatpak app tree.
install -Dm0755 \
    ".flatpak-release/rusttavern" \
    "$FLATPAK_DEST/bin/rusttavern"
cp -a src "$FLATPAK_DEST/bin/src"
cp -a default "$FLATPAK_DEST/bin/default"

# Launch wrapper: routes the data root to a writable XDG directory (the app
# tree under /app is read-only) and points the server at the packaged
# resources. Referenced as the manifest `command`.
install -Dm0755 \
    packaging/flatpak/rusttavern-wrapper.sh \
    "$FLATPAK_DEST/bin/rusttavern-wrapper"

# Render the desktop entry template: the source file ships with
# {{placeholders}} for bundlers, and desktop-file-validate rejects them.
desktop_dir="$FLATPAK_DEST/share/applications"
mkdir -p "$desktop_dir"
desktop_file="$desktop_dir/$APP_ID.desktop"
sed \
    -e "s#{{name}}#RustTavern#g" \
    -e "s#{{comment}}#Self-hosted SillyTavern HTTP server#g" \
    -e "s#{{exec}}#rusttavern#g" \
    -e "s#{{icon}}#${APP_ID}#g" \
    crates/rusttavern/bundle/linux/RustTavern.desktop \
    >"$desktop_file"
grep -F "{{" "$desktop_file" >/dev/null &&
    die "unrendered placeholder remains in the desktop entry" || true

# Flatpak apps need an icon referenced by the desktop entry; derive the
# standard sizes from the packaged frontend logo (no icon sources ship in
# the bundle/ directory).
icon_root="$FLATPAK_DEST/share/icons/hicolor"
for size in 128 256; do
    mkdir -p "$icon_root/${size}x${size}/apps"
    cp "src/img/logo.png" "$icon_root/${size}x${size}/apps/${APP_ID}.png"
done

metainfo="$FLATPAK_DEST/share/metainfo/$APP_ID.metainfo.xml"
install -Dm0644 \
    crates/rusttavern/bundle/linux/com.rusttavern.client.metainfo.xml \
    "$metainfo"
sed -i \
    "s#<launchable type=\"desktop-id\">RustTavern.desktop</launchable>#<launchable type=\"desktop-id\">$APP_ID.desktop</launchable>#" \
    "$metainfo"
grep -F "<launchable type=\"desktop-id\">$APP_ID.desktop</launchable>" "$metainfo" >/dev/null ||
    die "failed to normalize the AppStream launchable ID"

install -Dm0644 LICENSE "$FLATPAK_DEST/share/licenses/$APP_ID/LICENSE"

desktop-file-validate "$desktop_file"
appstreamcli validate --no-net "$metainfo"
